### ISSUE TITLE
Chromecast crash in android 10 Brand:samsung Model:Galaxy M20

### ISSUE THREAD

**Issue by rashmisridar** [whowillcare/flutter_cast_video#4]
Currently using the version of flutter_cast_video: ^1.2.0,  while clicking on the cast icon below error log I am receiving .

Device Info:-
Brand:samsung
Model:Galaxy M20

Fatal Exception: java.lang.IllegalArgumentException: background can not be translucent: #0        at androidx.core.graphics.a.d(ColorUtils.java:8)        at androidx.mediarouter.app.j.f(MediaRouterThemeHelper.java:2)        at androidx.mediarouter.app.j.l(MediaRouterThemeHelper.java:5)        at androidx.mediarouter.app.j.c(MediaRouterThemeHelper.java:2)        at androidx.mediarouter.app.b.<init>(MediaRouteChooserDialog.java:3)        at androidx.mediarouter.app.b.<init>(MediaRouteChooserDialog.java:1)        at androidx.mediarouter.app.c.g(MediaRouteChooserDialogFragment.java:1)        at androidx.mediarouter.app.c.onCreateDialog(MediaRouteChooserDialogFragment.java:4)        at androidx.fragment.app.c.prepareDialog(DialogFragment.java:4)        at androidx.fragment.app.c.onGetLayoutInflater(DialogFragment.java:3)        at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1)        at androidx.fragment.app.a0.f(FragmentStateManager.java:4)        at androidx.fragment.app.a0.m(FragmentStateManager.java:20)        at androidx.fragment.app.FragmentManager.g0(FragmentManager.java:31)        at androidx.fragment.app.FragmentManager.n1(FragmentManager.java:9)        at androidx.fragment.app.FragmentManager.d0(FragmentManager.java:4)        at androidx.fragment.app.FragmentManager$f.run(FragmentManager.java:1)        at android.os.Handler.handleCallback(Handler.java:883)        at android.os.Handler.dispatchMessage(Handler.java:100)        at android.os.Looper.loop(Looper.java:237)        at android.app.ActivityThread.main(ActivityThread.java:7807)        at java.lang.reflect.Method.invoke(Method.java)        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)

**Comment by mevljas** [comment]
As specified in the [README.md](https://github.com/whowillcare/flutter_cast_video/blob/main/README.md) file, you should use `@style/Theme.AppCompat.NoActionBar` theme or correctly implement the theme yourself. This is not a bug.
